# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'w_customers',
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('value', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'w_elements',
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
            },
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.FloatField(default=0)),
                ('subtotal_value', models.FloatField(default=0)),
                ('tax_value', models.FloatField(default=0)),
                ('neto_value', models.FloatField(default=0)),
                ('discount_value', models.FloatField(default=0)),
                ('total_value', models.FloatField(default=0)),
                ('valid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Customer')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'w_estimations',
                'verbose_name': 'Estimation',
                'verbose_name_plural': 'Estimations',
            },
        ),
        migrations.CreateModel(
            name='EstimationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.IntegerField(default=1)),
                ('hrs_labor', models.IntegerField(default=0)),
                ('val_labor', models.FloatField(default=0)),
                ('hrs_refinish', models.IntegerField(default=0)),
                ('val_refinish', models.FloatField(default=0)),
                ('hrs_frame', models.IntegerField(default=0)),
                ('val_frame', models.FloatField(default=0)),
                ('hrs_mechanical', models.IntegerField(default=0)),
                ('val_mechanical', models.FloatField(default=0)),
                ('hrs_paint', models.IntegerField(default=0)),
                ('val_paint', models.FloatField(default=0)),
                ('hrs_total', models.IntegerField(default=0)),
                ('val_total', models.FloatField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Element')),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Estimation')),
            ],
            options={
                'ordering': ('estimation', 'element'),
                'db_table': 'w_estimations_details',
                'verbose_name': 'Estimation Detail',
                'verbose_name_plural': 'Estimation Details',
            },
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('name',)]),
        ),
    ]
